{{- if not .Values.rbac.watchAllNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ default "klogs-viewer" .Values.rbac.role.name }}
  namespace: {{ include "chart.namespace" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ default "klogs-viewer" .Values.rbac.role.name }}
  namespace: {{ include "chart.namespace" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ default "klogs-viewer" .Values.serviceAccount.name }}
  namespace: {{ include "chart.namespace" . }}
roleRef:
  kind: Role
  name: {{ default "klogs-viewer" .Values.rbac.role.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}