{{- if .Values.application.authEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: klogs-viewer
  namespace: {{ include "chart.namespace" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.application.authToken | default (randAlphaNum 32) | b64enc }}
{{- end }}
